<?php

use App\Http\Controllers\AdmainController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\ComplaintController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\InformationController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\WeeklyScheduleController;
use App\Http\Controllers\ClassroomController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\MarkController;
use App\Http\Controllers\HomeworkController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

Route::post('login',[UserController::class,'login']);
Route::post('logout',[UserController::class,'logout'])->middleware('auth:sanctum');
Route::post('forgetPassword',[UserController::class,'forgetPassword']);
Route::post('userCheckCode',[UserController::class,'userCheckCode']);
Route::post('resetPassword',[UserController::class,'resetPassword']);
Route::post('addStudent',[StudentController::class,'addStudent']);
Route::get('getGrades', [GradeController::class, 'getGrades']);
Route::post('updateStudent/{userId}',[StudentController::class,'updateStudent']);
Route::delete('destroyStudent/{userId}',[StudentController::class,'destroyStudent']);
Route::get('showStudent',[StudentController::class,'showStudent'])->middleware('auth:sanctum');;
Route::put('updateAccount',[UserController::class,'updateAccount']);
Route::post('deleteUser',[UserController::class,'deleteUser']);
Route::post('addTeacher',[TeacherController::class,'addTeacher']);
Route::post('updateTeacher/{userId}',[TeacherController::class,'updateTeacher']);
Route::delete('destroyTeacher/{userId}',[TeacherController::class,'destroyTeacher']);
Route::get('getTeacher',[TeacherController::class,'getTeacher']);
Route::post('addAdmain',[AdmainController::class,'addAdmain']);
Route::post('updateAdmain/{userId}',[AdmainController::class,'updateAdmain']);
Route::delete('destroyAdmin/{id}',[AdmainController::class,'destroyAdmin']);
Route::get('getAdmin',[AdmainController::class,'getAdmin']);
Route::post('addEmployee',[EmployeeController::class,'addEmployee']);
Route::post('updateEmployee/{userId}',[EmployeeController::class,'updateEmployee']);
Route::get('showEmployee',[EmployeeController::class,'showEmployee']);
Route::post('addInfo', [InformationController::class, 'storeInfo']);
Route::get('getInfo', [InformationController::class, 'getInfo']);
Route::post('updateInfo', [InformationController::class, 'updateInfo']);
Route::post('addNews', [NewsController::class, 'storeNews']);
Route::post('updateNews/{id}', [NewsController::class, 'updateNews']);
Route::get('getAllNews', [NewsController::class, 'getAllNews']);
Route::get('getNews', [NewsController::class, 'getNews'])->middleware('auth:sanctum');
Route::delete('deleteNews/{id}', [NewsController::class, 'deleteNews']);
Route::post('addComplaint', [ComplaintController::class, 'addComplaint'])->middleware('auth:sanctum');
Route::post('updateComplaint/{id}', [ComplaintController::class, 'updateComplaint'])->middleware('auth:sanctum');
Route::delete('deleteComplaint/{id}', [ComplaintController::class, 'deleteComplaint'])->middleware('auth:sanctum');
Route::get('getComplaints', [ComplaintController::class, 'getComplaints'])->middleware('auth:sanctum');
Route::get('getComplaintsByGrade/{gradeId}', [ComplaintController::class, 'getComplaintsByGrade']);
Route::post('takeAbsences', [AttendanceController::class, 'takeAbsences']);
Route::get('getAbsenceCountBySection/{grade_id}/{classroom_id}', [AttendanceController::class, 'getAbsenceCountBySection']);
Route::get('getStudentAbsences/{studentId}', [AttendanceController::class, 'getStudentAbsences']);
Route::get('getStudentAbsencesMobile', [AttendanceController::class, 'getStudentAbsencesMobile'])->middleware('auth:sanctum');
Route::get('getTeacherWeeklySchedule', [WeeklyScheduleController::class, 'getTeacherWeeklySchedule'])->middleware('auth:sanctum');
Route::post('uploadFile', [FileController::class, 'uploadFile'])->middleware('auth:sanctum');
Route::post('updateFile/{id}', [FileController::class, 'updateFile'])->middleware('auth:sanctum');
Route::delete('deleteFile/{id}', [FileController::class, 'deleteFile'])->middleware('auth:sanctum');
Route::get('restoreFile/{id}', [FileController::class, 'restoreFile'])->middleware('auth:sanctum');
Route::delete('forceDeleteFile/{id}', [FileController::class, 'forceDeleteFile'])->middleware('auth:sanctum');
Route::get('trashedFiles', [FileController::class, 'trashedFiles'])->middleware('auth:sanctum');
Route::get('listFiles', [FileController::class, 'listFiles'])->middleware('auth:sanctum');
Route::get('getFilesBySubjectForStudent', [FileController::class, 'getFilesBySubjectForStudent'])->middleware('auth:sanctum');
Route::get('getFilesByTeacherId/{teacher_id}', [FileController::class, 'getFilesByTeacherId']);


Route::post('addNote', [NoteController::class, 'storeNote']);
Route::post('updateNote/{id}', [NoteController::class, 'update']);
Route::delete('deleteNote/{id}', [NoteController::class, 'destroy']);
Route::get('allnoteStudent', [NoteController::class, 'allnoteStudent'])->middleware('auth:sanctum');
Route::get('getNoteStudent/{id}', [NoteController::class, 'getNoteStudent']);
Route::get('getStudentsByGradeAndClassroom/{gradeId}/{sectionId}', [StudentController::class, 'getStudentsByGradeAndClassroom']);
Route::post('storeWeeklySchedule', [WeeklyScheduleController::class, 'storeWeeklySchedule']);
Route::get('getWeeklySchedule', [WeeklyScheduleController::class, 'getWeeklySchedule'])->middleware('auth:sanctum');
Route::get('getClassroomsByGrade/{gradeId}', [ClassroomController::class, 'getClassroomsByGrade']);
Route::get('getSubject', [SubjectController::class, 'getSubject']);
Route::get('getTeachersBySubject/{subject_id}', [TeacherController::class, 'getTeachersBySubject']);
Route::get('showWeeklySchedule', [WeeklyScheduleController::class, 'showWeeklySchedule']);
Route::post('updateWeeklySchedule', [WeeklyScheduleController::class, 'updateWeeklySchedule']);
Route::delete('deleteWeeklySchedule', [WeeklyScheduleController::class, 'deleteWeeklySchedule']);
Route::post('storeMarks', [MarkController::class, 'storeMarks']);
Route::get('getStudentMarks', [MarkController::class, 'getStudentMarks'])->middleware('auth:sanctum');
Route::get('showStudentsWithMarks', [MarkController::class, 'showStudentsWithMarks']);
Route::post('addHomework', [HomeworkController::class, 'addHomework']);
Route::post('updateHomework/{id}', [HomeworkController::class, 'updateHomework']);
Route::delete('deleteHomework/{id}', [HomeworkController::class, 'deleteHomework']);
Route::get('getHomeworksByClassroomAndSubject/{classroom_id}/{subject_id}', [HomeworkController::class, 'getHomeworksByClassroomAndSubject']);
Route::get('getStudentHomeworks', [HomeworkController::class, 'getStudentHomeworks'])->middleware('auth:sanctum');
Route::get('showTeacher',[TeacherController::class,'showTeacher'])->middleware('auth:sanctum');
